### ISSUE TITLE
3.0.0 - cannot load such file -- dbus/systemd/machined

### ISSUE THREAD

**Issue by grogancolin** [nathwill/chef-systemd#105]
Since updating to 3.0.0 - we've had some cookbooks fail to run with:

```
Failure/Error: let(:chef_run) { solo_runner(platform, version).converge(described_recipe) }

     LoadError:
        cannot load such file -- dbus/systemd/machined
```

**Comment by nathwill** [comment]
hmmm, so this cookbook uses the 'gem' method in the metadata to install the dbus-systemd gem, which seems to be the issue here. i'm guessing you're using an older version of chef? i believe this should be resolvable by doing a compile-time installation with a chef_gem resource for dbus-systemd, or upgrading to a chef version that supports the gem method during the metadata parsing.

let me know if i can be of further assistance.

**Comment by nathwill** [comment]
i'm updating our metadata to specify that we require a chef_version >= 12.8.1, which is when the [gem metadata support](https://github.com/chef/chef/pull/4478) was added to chef core

**Comment by mpires** [comment]
Weird, I'm getting the same issue running with Chef 13.2.20, with `systemd` 3.0.1
```
googlecompute: cannot load such file -- dbus/systemd/machined
    googlecompute:
    googlecompute: Cookbook Trace:
    googlecompute: ---------------
    googlecompute: /var/chef/cache/cookbooks/systemd/resources/machine.rb:1:in `class_from_file'
    googlecompute:
    googlecompute: Relevant File Content:
    googlecompute: ----------------------
    googlecompute: /var/chef/cache/cookbooks/systemd/resources/machine.rb:
    googlecompute:
    googlecompute: 1>> require 'dbus/systemd/machined'
```

**Comment by mpires** [comment]
With systemd 3.0.1
```
googlecompute: cannot load such file -- dbus/systemd/machined
    googlecompute:
    googlecompute: Cookbook Trace:
    googlecompute: ---------------
    googlecompute: /var/chef/cache/cookbooks/systemd/resources/machine.rb:1:in `class_from_file'
    googlecompute:
    googlecompute: Relevant File Content:
    googlecompute: ----------------------
    googlecompute: /var/chef/cache/cookbooks/systemd/resources/machine.rb:
    googlecompute:
    googlecompute: 1>> require 'dbus/systemd/machined'
```
